### ISSUE TITLE
add configuration command

### ISSUE THREAD

**Issue by cedrata** [cedrata/jira-helper#27]
provide a a new sub command to configure the CLI to provide the following functionalities:
- add a profile
- update a profile values
- delete a profile

**Comment by kadinsayani** [comment]
Hi, I'm interested in working on this issue. To clarify, by add a profile do you meed add a user? I don't see a profile endpoint in the api spec.

**Comment by cedrata** [comment]
Hi @kadinsayani, thank you for the interest, I wasn't expecting to have someone interested in it!

So, what I mean is to have a configuration file structured like the following one:
```ini
[profile1]
token=foo
host=bar.com

[profile2]
token=baz
host=roo.com
```

It is not a feature of the Jira REST API itself but it would be something client side to handle a situation where you, developer, are jumping around multiple projects and to avoid changing all the time the configuration file or providing every time the different credentials you can use a flag `--profile` and select the host and token from one of the different profiles saved inside the configuration file. 

The behaviour would be similar to the AWS CLI configuration file, you can take a look on how it works [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-format-profile)

As written in the issue a user should be able to add, update and delete a profile, a default profile can be available and if no profile is specified then the default one should be used.

The command could be structured as:
```bash
$ jira-helper configure # create a new profile, edit a specific profile or the default one
$ jira-helper delete # delete the given profile 
```

So a new subcommand inside of `cmd/root.go` could be added and a new directory named `cmd/configure` can also be added with two file `configure.go` and `delete.go` to manage the two sub commands.

You can take inspiration from the already available commands and subcommands.

I hope this clarify the expected behaviour of the feature.
Have fun!🦄

**Comment by cedrata** [comment]
Hi @kadinsayani I can see your pull request, I will review it as soon as possible unfortunately this week turns out busier than expected. I hope you can understand!

**Comment by kadinsayani** [comment]
No worries! Thanks :)
